backend:
  name: github
  repo: sulenchy/decap-cms-react-demo
  branch: main
media_folder: "public/images/uploads"
collections:
  - name: "content"
    label: "Content"
    files:
      - label: "English"
        name: "en"
        file: "public/locales/en/translation.json"
        fields:
          - { label: "About Page", name: "about", widget: "object", fields: [ { label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" } ] }
          - { label: "Home Page", name: "home", widget: "object", fields: [ { label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" } ] }
          - label: "Blog"
            name: "blog"
            widget: "list"
            fields:
              - { label: "Slug", name: "slug", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Thumbnail", name: "thumbnail", widget: "image" }
              - { label: "Rating", name: "rating", widget: "number" }
              - { label: "Body", name: "body", widget: "markdown" }
      - label: "French"
        name: "fr"
        file: "public/locales/fr/translation.json"
        fields:
          - { label: "About Page", name: "about", widget: "object", fields: [ { label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" } ] }
          - { label: "Home Page", name: "home", widget: "object", fields: [ { label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" } ] }
          - label: "Blog"
            name: "blog"
            widget: "list"
            fields:
              - { label: "Slug", name: "slug", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Thumbnail", name: "thumbnail", widget: "image" }
              - { label: "Rating", name: "rating", widget: "number" }
              - { label: "Body", name: "body", widget: "markdown" }
      - label: "German"
        name: "de"
        file: "public/locales/de/translation.json"
        fields:
          - { label: "About Page", name: "about", widget: "object", fields: [ { label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" } ] }
          - { label: "Home Page", name: "home", widget: "object", fields: [ { label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" } ] }
          - label: "Blog"
            name: "blog"
            widget: "list"
            fields:
              - { label: "Slug", name: "slug", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Thumbnail", name: "thumbnail", widget: "image" }
              - { label: "Rating", name: "rating", widget: "number" }
              - { label: "Body", name: "body", widget: "markdown" }